### PR TITLE
Matrix pilot mw4fbw

### PR DESCRIPTION
**Pull request by phollands**

### CODE REVIEW

**Comment by phollands** [comment]
Did I actually make a Pull Request ? Or did you just decide to Pull ?

Best wishes, Pete

**Comment by kd0aij** [comment]
Pete,

:) I found a pull request in my email. And I was going to ask you how to do
it, because I've never tried :)

---

You can merge this Pull Request by running

  git pull https://github.com/phollands/MatrixPilot MatrixPilot_mw4fbw

Or view, comment on, or merge it at:

  https://github.com/kd0aij/MatrixPilot/pull/1
Commit Summary
- Initial change to flan.pyw to add a Google Earth Layer for X
  acceleration Vectors in body of plane
- Plot X accel vector only 5 meters above flight path insteda of 15;
  negate pitch value on vector's roll.

File Changes
- _M_ Tools/flight_analyzer/flan.pyw
  https://github.com/kd0aij/MatrixPilot/pull/1/files#diff-0 (101)
- _M_ Tools/flight_analyzer/matrixpilot_lib.py
  https://github.com/kd0aij/MatrixPilot/pull/1/files#diff-1 (9)

Patch Links:
- https://github.com/kd0aij/MatrixPilot/pull/1.patch
- https://github.com/kd0aij/MatrixPilot/pull/1.diff

---

I just copied the git command in the email above and pushed the result.
The python code runs fine for me here.

73, Mark

On Sun, Sep 14, 2014 at 11:29 PM, Pete Hollands notifications@github.com
wrote:

> Did I actually make a Pull Request ? Or did you just decide to Pull ?
> 
> Best wishes, Pete
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55554001.

## 

Mark Whitehorn
kd0aij@gmail.com

**Comment by phollands** [comment]
OK, Well I did look at a commit diff on my part of the github  website, and
I did press on Pull Request.

That then gave me a chance to add some comments (which I did not do), and
then I was not aware that I saved the request.

I will be more careful next time. But no harm done I think. The code is
prototyped and useful but not yet fully tested and validated.

Best wishes, Pete

**Comment by kd0aij** [comment]
Pete,

It looks like that might be the easiest way for us to collaborate; no need
for me to maintain a separate clone of your fork if I can easily merge your
changes to my repo.  It looks symmetric too; it's just "pull _remotename
branchname"_ to stay up to date with another repo. And it's nice to get an
email letting one know of changes in other forks.

73, Mark

On Mon, Sep 15, 2014 at 9:00 AM, Pete Hollands notifications@github.com
wrote:

> OK, Well I did look at a commit diff on my part of the github website, and
> I did press on Pull Request.
> 
> That then gave me a chance to add some comments (which I did not do), and
> then I was not aware that I saved the request.
> 
> I will be more careful next time. But no harm done I think. The code is
> prototyped and useful but not yet fully tested and validated.
> 
> Best wishes, Pete
> 
> On 15 September 2014 13:31, Mark Whitehorn notifications@github.com
> wrote:
> 
> > Pete,
> > 
> > :) I found a pull request in my email. And I was going to ask you how to
> > do
> > it, because I've never tried :)
> > 
> > ---
> > 
> > You can merge this Pull Request by running
> > 
> > git pull https://github.com/phollands/MatrixPilot MatrixPilot_mw4fbw
> > 
> > Or view, comment on, or merge it at:
> > 
> > https://github.com/kd0aij/MatrixPilot/pull/1
> > Commit Summary
> > - Initial change to flan.pyw to add a Google Earth Layer for X
> >   acceleration Vectors in body of plane
> > - Plot X accel vector only 5 meters above flight path insteda of 15;
> >   negate pitch value on vector's roll.
> > 
> > File Changes
> > - _M_ Tools/flight_analyzer/flan.pyw
> >   https://github.com/kd0aij/MatrixPilot/pull/1/files#diff-0 (101)
> > - _M_ Tools/flight_analyzer/matrixpilot_lib.py
> >   https://github.com/kd0aij/MatrixPilot/pull/1/files#diff-1 (9)
> > 
> > Patch Links:
> > - https://github.com/kd0aij/MatrixPilot/pull/1.patch
> > - https://github.com/kd0aij/MatrixPilot/pull/1.diff
> > 
> > ---
> > 
> > I just copied the git command in the email above and pushed the result.
> > The python code runs fine for me here.
> > 
> > 73, Mark
> > 
> > On Sun, Sep 14, 2014 at 11:29 PM, Pete Hollands <
> > notifications@github.com>
> > 
> > wrote:
> > 
> > > Did I actually make a Pull Request ? Or did you just decide to Pull ?
> > > 
> > > Best wishes, Pete
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55554001.
> > 
> > ## 
> > 
> > Mark Whitehorn
> > kd0aij@gmail.com
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55583532.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55602960.

## 

Mark Whitehorn
kd0aij@gmail.com

**Comment by kd0aij** [comment]
Pete,

I've created a new branch in my git repo, name is shortened to just "mw4",
for testing with SILsim. (was forced to do this because SILsim worked in
_mw4 but not _mw4fbw and I couldn't see what the problem was)

At the moment, SILsim is working well with Xplane9 on 64bit Ubuntu. The SIL
executable is Tools/MatrixPilot-SIL/matrixpilot and it was built using the
command "make -f Makefile.unix matrixpilot" (need to do a "clean" first, if
you change any library files).

The options file for the build is
"Tools/MatrixPilot-SIL/projectSpecific/options.h" and the plugin I'm using
is "Tools/HILSIM_XPlane/prebuilt-plugins/HILSIM-linux_129.xpl"

I noticed some discrepancies between the artificial horizons displayed in
Xplane and QGC (pitch appears to be 5-10 degrees to nose-high in QGC), and
that the plugin was using the "red board" value for scaleaccel. But
changing that value didn't seem to make any difference; perhaps it doesn't
matter, but it look to me as though it should.

Anyway, the simulated PT60 is flying a Logo flightplan pretty nicely using
angle setpoints for roll and pitch, and it would be nice to see whether
anyone could replicate my results.

Also, if the Xplane artificial horizon is "ground truth", then this may
indicate a bug in the IMU, at least in my branch. I'd like to do the same
comparison using trunk, but haven't been able to make the PT60 fly at all
in trunk SILsim. Perhaps someone else is current with the changes to trunk
SILsim and can provide some advice.

73, Mark

On Mon, Sep 15, 2014 at 9:48 AM, Mark Whitehorn kd0aij@gmail.com wrote:

> Pete,
> 
> It looks like that might be the easiest way for us to collaborate; no need
> for me to maintain a separate clone of your fork if I can easily merge your
> changes to my repo.  It looks symmetric too; it's just "pull _remotename
> branchname"_ to stay up to date with another repo. And it's nice to get
> an email letting one know of changes in other forks.
> 
> 73, Mark
> 
> On Mon, Sep 15, 2014 at 9:00 AM, Pete Hollands notifications@github.com
> wrote:
> 
> > OK, Well I did look at a commit diff on my part of the github website,
> > and
> > I did press on Pull Request.
> > 
> > That then gave me a chance to add some comments (which I did not do), and
> > then I was not aware that I saved the request.
> > 
> > I will be more careful next time. But no harm done I think. The code is
> > prototyped and useful but not yet fully tested and validated.
> > 
> > Best wishes, Pete
> > 
> > On 15 September 2014 13:31, Mark Whitehorn notifications@github.com
> > wrote:
> > 
> > > Pete,
> > > 
> > > :) I found a pull request in my email. And I was going to ask you how
> > > to
> > > do
> > > it, because I've never tried :)
> > > 
> > > ---
> > > 
> > > You can merge this Pull Request by running
> > > 
> > > git pull https://github.com/phollands/MatrixPilot MatrixPilot_mw4fbw
> > > 
> > > Or view, comment on, or merge it at:
> > > 
> > > https://github.com/kd0aij/MatrixPilot/pull/1
> > > Commit Summary
> > > - Initial change to flan.pyw to add a Google Earth Layer for X
> > >   acceleration Vectors in body of plane
> > > - Plot X accel vector only 5 meters above flight path insteda of 15;
> > >   negate pitch value on vector's roll.
> > > 
> > > File Changes
> > > - _M_ Tools/flight_analyzer/flan.pyw
> > >   https://github.com/kd0aij/MatrixPilot/pull/1/files#diff-0 (101)
> > > - _M_ Tools/flight_analyzer/matrixpilot_lib.py
> > >   https://github.com/kd0aij/MatrixPilot/pull/1/files#diff-1 (9)
> > > 
> > > Patch Links:
> > > - https://github.com/kd0aij/MatrixPilot/pull/1.patch
> > > - https://github.com/kd0aij/MatrixPilot/pull/1.diff
> > > 
> > > ---
> > > 
> > > I just copied the git command in the email above and pushed the result.
> > > The python code runs fine for me here.
> > > 
> > > 73, Mark
> > > 
> > > On Sun, Sep 14, 2014 at 11:29 PM, Pete Hollands <
> > > notifications@github.com>
> > > 
> > > wrote:
> > > 
> > > > Did I actually make a Pull Request ? Or did you just decide to Pull ?
> > > > 
> > > > Best wishes, Pete
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55554001.
> > > 
> > > ## 
> > > 
> > > Mark Whitehorn
> > > kd0aij@gmail.com
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55583532.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55602960.
> 
> ## 
> 
> Mark Whitehorn
> kd0aij@gmail.com

## 

Mark Whitehorn
kd0aij@gmail.com

**Comment by phollands** [comment]
Hi Mark,

In parallel to your efforts last night, I also did some debugging of SILSIM
for Helical Turns on MacOS with Xplane 10, but using 32bit binaries, on a
64 bit imac.

In my case, and with my options.h file, I have a bug where aileron value on
pwOut[] gets set to a maximum value (2000) when it should be moving from
3000 (neutral) to -5% of aileron.

I have established two facts:-
1) SILSIM is actually moving to stabilised mode on "GPS acquired
(incorrectly)". On GPS acquired is briefly moving to Manual, and then
straight on to Stabilised.
I have no transmitter connected, and I am only using a keyboard. I am not
requesting stabilised mode. If I press "1" I move correctly back to manual
mode from stabilised.
2) The bug I am seeing is only happening in Stabilised mode. So it could be
just a bug associated with Helical Turns. (I have not tested waypoint mode
yet).

Tonight I was going to take trunk, and compare results with trunk. (I am
commuting to London today).

I have just tried to install X-Plane on Ubuntu 12.04 under Parallels and it
does not like it. It says:-
"Whoah -- no matter how hard I tried, I failed to get a GLX visual.
Something's seriously wonky on your machine."
So looks like I will have only run X-Plane10 natively on my Imac.

Best wishes, Pete

**Comment by kd0aij** [comment]
Mark,
It vaguely recall from when I was working on the Xplane plug-in that Xplane
was using a different definition of pitch then what we are using in
MatrixPilot. I think they differ by the angle of attack, but I may be wrong
about that. I think that Xplane defines pitch angle as the angle between
the trajectory of the plane and the horizontal. When I get a chance, I will
go back and look. MatrixPilot uses 0 for the angle of attack. One of the
things on my list of things to do is to build a model for estimating angle
of attack. I think we could come up with a reasonably simple model that
would provide reasonable accuracy.
In the meantime, I will check the logs from my recent HILSIM tests with the
B747 and see what the relationships are. I do know that Xplane 10 displays
both the pitch attitude of the aircraft as well as the pitch attitude of
the trajectory.
Best regards,
Bill

**Comment by kd0aij** [comment]
Mark,
I went back and looked at my HILSIM logs for the B747 flight to refresh my
memory. Here is what the IMU measures for pitch angle: it is the angle
between Y axis of the board and the earth horizontal plane. For HILSIM, the
angle is zero when the plane is on the ground. In my HILSIM logs, the pitch
angle shows as 0 prior to takeoff. During flight, it continues to display
the angle between board Y axis and horizontal. In my simulations, when the
controls lock onto constant altitude and speed, the pitch displayed by
MatrixPIlot is exactly the same as attitude pitch displayed by Xplane 10,
it is the angle of attack of the aircraft. For a B747 at cruising speed,
that come out to be a couple of degrees.
You might want to take a look at the attached log file for one of the
HILSIM B747 flights.
What the UDB measures in real flight for pitch angle is the angle between Y
axis of the board and earth horizontal plane, provided the accelerometer
offsets are recorded when the board is level.
Best regards,
Bill

**Comment by kd0aij** [comment]
Mark,

A couple of other things to note in the file that I sent you:
1. The initial value of pitch on the ground is 1 degree, but quickly decays
   to 0, and stays at zero prior to takeoff. The initial value of 1 degree is
   probably due to round off somewhere in the computations, but the IMU drift
   compensation picks up on it and nulls it out.
2. During straight and level flight at constant speed and altitude, the IMU
   pitch is around 1 or 2 degrees, which is the same value that Xplane
   displayed.
3. I have set up the gains for the B747 controls to fly rather fast. This
   results in rather low values of angle of attack in level flight of 1 to 2
   degrees.
4. During turns you will see the pitch angle go up quite a bit, sometimes
   as much as 10 degrees. This agrees with what I saw in the Xplane10 heads up
   display, and agrees with increased angle of attack displayed during a turn,
   no doubt due to increased wing loading.

Best regards,
Bill

**Comment by kd0aij** [comment]
Mark,

A couple more comments on the subject of IMU attitude accuracy:

A non-zero angle of attack does cause some small error in the centrifugal
compensation computations during a turn. There are two ways of reducing
that error:
1. Use the method I describe here
   http://diydrones.com/forum/topics/an-improved-method-for-accounting-for-acceleration-in-gyro-roll.
   This is the method presently used in ArduPilot. I helped the Ardu team get
   it working. Under some conditions it can diverge, it is a little be tricky
   to get it working reliably. It is a must to have for multicopters, but is
   not really needed for fixed wing. I released a beta version of it for
   MatrixPilot. Ric tested it out and felt it was not working very well, so I
   retracted it.
2. Use a model to compute angles of attack and side slip from airspeed and
   wing loading. I intend to implement this approach for MatrixPilot. For
   fixed wing, I think that is the best way to go. The method will not work
   for multicopters.

Best regards,
Bill

**Comment by kd0aij** [comment]
Bill,

Thanks for all the info. I guess I'll first configure SILsim in my branch
for the 747 and see whether the discrepancy is still there.

Regarding your improved centrifugal compensation method, I vaguely recall
porting it into my Multi branch a year or two back, but not having much
success with it. I don't recall Ric's testing, but then I wasn't flying any
fixed-wing aircraft on MatrixPilot at the time.

73, Mark

On Mon, Sep 29, 2014 at 8:01 AM, William Premerlani wpremerlani@gmail.com
wrote:

> Mark,
> 
> A couple more comments on the subject of IMU attitude accuracy:
> 
> A non-zero angle of attack does cause some small error in the centrifugal
> compensation computations during a turn. There are two ways of reducing
> that error:
> 1. Use the method I describe here
>    http://diydrones.com/forum/topics/an-improved-method-for-accounting-for-acceleration-in-gyro-roll.
>    This is the method presently used in ArduPilot. I helped the Ardu team get
>    it working. Under some conditions it can diverge, it is a little be tricky
>    to get it working reliably. It is a must to have for multicopters, but is
>    not really needed for fixed wing. I released a beta version of it for
>    MatrixPilot. Ric tested it out and felt it was not working very well, so I
>    retracted it.
> 2. Use a model to compute angles of attack and side slip from airspeed and
>    wing loading. I intend to implement this approach for MatrixPilot. For
>    fixed wing, I think that is the best way to go. The method will not work
>    for multicopters.
> 
> Best regards,
> Bill
> 
> On Sun, Sep 28, 2014 at 10:35 PM, Mark Whitehorn kd0aij@gmail.com wrote:
> 
> > Pete,
> > 
> > I've created a new branch in my git repo, name is shortened to just
> > "mw4", for testing with SILsim. (was forced to do this because SILsim
> > worked in _mw4 but not _mw4fbw and I couldn't see what the problem was)
> > 
> > At the moment, SILsim is working well with Xplane9 on 64bit Ubuntu. The
> > SIL executable is Tools/MatrixPilot-SIL/matrixpilot and it was built using
> > the command "make -f Makefile.unix matrixpilot" (need to do a "clean"
> > first, if you change any library files).
> > 
> > The options file for the build is
> > "Tools/MatrixPilot-SIL/projectSpecific/options.h" and the plugin I'm using
> > is "Tools/HILSIM_XPlane/prebuilt-plugins/HILSIM-linux_129.xpl"
> > 
> > I noticed some discrepancies between the artificial horizons displayed in
> > Xplane and QGC (pitch appears to be 5-10 degrees to nose-high in QGC), and
> > that the plugin was using the "red board" value for scaleaccel. But
> > changing that value didn't seem to make any difference; perhaps it doesn't
> > matter, but it look to me as though it should.
> > 
> > Anyway, the simulated PT60 is flying a Logo flightplan pretty nicely
> > using angle setpoints for roll and pitch, and it would be nice to see
> > whether anyone could replicate my results.
> > 
> > Also, if the Xplane artificial horizon is "ground truth", then this may
> > indicate a bug in the IMU, at least in my branch. I'd like to do the same
> > comparison using trunk, but haven't been able to make the PT60 fly at all
> > in trunk SILsim. Perhaps someone else is current with the changes to trunk
> > SILsim and can provide some advice.
> > 
> > 73, Mark
> > 
> > On Mon, Sep 15, 2014 at 9:48 AM, Mark Whitehorn kd0aij@gmail.com wrote:
> > 
> > > Pete,
> > > 
> > > It looks like that might be the easiest way for us to collaborate; no
> > > need for me to maintain a separate clone of your fork if I can easily merge
> > > your changes to my repo.  It looks symmetric too; it's just "pull _remotename
> > > branchname"_ to stay up to date with another repo. And it's nice to get
> > > an email letting one know of changes in other forks.
> > > 
> > > 73, Mark
> > > 
> > > On Mon, Sep 15, 2014 at 9:00 AM, Pete Hollands <notifications@github.com
> > > 
> > > > wrote:
> > > > 
> > > > OK, Well I did look at a commit diff on my part of the github website,
> > > > and
> > > > I did press on Pull Request.
> > > > 
> > > > That then gave me a chance to add some comments (which I did not do),
> > > > and
> > > > then I was not aware that I saved the request.
> > > > 
> > > > I will be more careful next time. But no harm done I think. The code is
> > > > prototyped and useful but not yet fully tested and validated.
> > > > 
> > > > Best wishes, Pete
> > > > 
> > > > On 15 September 2014 13:31, Mark Whitehorn notifications@github.com
> > > > wrote:
> > > > 
> > > > > Pete,
> > > > > 
> > > > > :) I found a pull request in my email. And I was going to ask you how
> > > > > to
> > > > > do
> > > > > it, because I've never tried :)
> > > > > 
> > > > > ---
> > > > > 
> > > > > You can merge this Pull Request by running
> > > > > 
> > > > > git pull https://github.com/phollands/MatrixPilot MatrixPilot_mw4fbw
> > > > > 
> > > > > Or view, comment on, or merge it at:
> > > > > 
> > > > > https://github.com/kd0aij/MatrixPilot/pull/1
> > > > > Commit Summary
> > > > > - Initial change to flan.pyw to add a Google Earth Layer for X
> > > > >   acceleration Vectors in body of plane
> > > > > - Plot X accel vector only 5 meters above flight path insteda of 15;
> > > > >   negate pitch value on vector's roll.
> > > > > 
> > > > > File Changes
> > > > > - _M_ Tools/flight_analyzer/flan.pyw
> > > > >   https://github.com/kd0aij/MatrixPilot/pull/1/files#diff-0 (101)
> > > > > - _M_ Tools/flight_analyzer/matrixpilot_lib.py
> > > > >   https://github.com/kd0aij/MatrixPilot/pull/1/files#diff-1 (9)
> > > > > 
> > > > > Patch Links:
> > > > > - https://github.com/kd0aij/MatrixPilot/pull/1.patch
> > > > > - https://github.com/kd0aij/MatrixPilot/pull/1.diff
> > > > > 
> > > > > ---
> > > > > 
> > > > > I just copied the git command in the email above and pushed the
> > > > > result.
> > > > > The python code runs fine for me here.
> > > > > 
> > > > > 73, Mark
> > > > > 
> > > > > On Sun, Sep 14, 2014 at 11:29 PM, Pete Hollands <
> > > > > notifications@github.com>
> > > > > 
> > > > > wrote:
> > > > > 
> > > > > > Did I actually make a Pull Request ? Or did you just decide to Pull
> > > > > > ?
> > > > > > 
> > > > > > Best wishes, Pete
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55554001.
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Mark Whitehorn
> > > > > kd0aij@gmail.com
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55583532.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55602960.
> > > 
> > > ## 
> > > 
> > > Mark Whitehorn
> > > kd0aij@gmail.com
> > 
> > ## 
> > 
> > Mark Whitehorn
> > kd0aij@gmail.com

## 

Mark Whitehorn
kd0aij@gmail.com

**Comment by kd0aij** [comment]
Hi Mark,

I've been succcessfully testing both trunk and Bill's branch with
HILSIM(AUAV3), SILSIM and X-Plane9 with the Cessna 172. However i'm
currently only running under windows so not sure how much i could help.

Cheers, Robert.

**Comment by kd0aij** [comment]
Robert,

It looks like there is no current options.h file for SILsim in the
helicalTurns branch.

Using the example B747 HILSIM options, I get compilation errors. Maybe I'd
have better luck with the options.h you're using? I'm not sure if it's in
the repo.

thanks, Mark

In file included from ../../MatrixPilot/mp_osd.c:30:0:
../../MatrixPilot/osd_config.h:23:0: warning: "USE_OSD" redefined [enabled
by default]
 #define USE_OSD         OSD_NONE
 ^
In file included from ../../MatrixPilot/../libDCM/../libUDB/libUDB.h:29:0,
                 from ../../MatrixPilot/../libDCM/libDCM.h:26,
                 from ../../MatrixPilot/defines.h:24,
                 from ../../MatrixPilot/mp_osd.c:22:
../../MatrixPilot/options.h:345:0: note: this is the location of the
previous definition
 #define USE_OSD                             0
 ^
gcc -c -pipe -Wall -W -O0 -DNIX=1 -I. -I../../libUDB -I../../libDCM
-I../../MatrixPilot -o ../../MatrixPilot/navigate.o
../../MatrixPilot/navigate.c
../../MatrixPilot/navigate.c: In function ‘init_navigation’:
../../MatrixPilot/navigate.c:69:28: error: ‘TURN_RATE_NAV’ undeclared
(first use in this function)
  turngainnav = (uint16_t)((TURN_RATE_NAV/57.3)_RMAX);
                            ^
../../MatrixPilot/navigate.c:69:28: note: each undeclared identifier is
reported only once for each function it appears in
../../MatrixPilot/navigate.c:70:28: error: ‘TURN_RATE_FBW’ undeclared
(first use in this function)
  turngainfbw = (uint16_t)((TURN_RATE_FBW/57.3)_RMAX);
                            ^
make: **\* [../../MatrixPilot/navigate.o] Error 1

On Mon, Sep 29, 2014 at 9:11 AM, Robert Dickenson <
robert.dickenson@gmail.com> wrote:

> Hi Mark,
> 
> I've been succcessfully testing both trunk and Bill's branch with
> HILSIM(AUAV3), SILSIM and X-Plane9 with the Cessna 172. However i'm
> currently only running under windows so not sure how much i could help.
> 
> Cheers, Robert.
> 
> On 29 September 2014 12:35, Mark Whitehorn kd0aij@gmail.com wrote:
> 
> > Pete,
> > 
> > I've created a new branch in my git repo, name is shortened to just
> > "mw4", for testing with SILsim. (was forced to do this because SILsim
> > worked in _mw4 but not _mw4fbw and I couldn't see what the problem was)
> > 
> > At the moment, SILsim is working well with Xplane9 on 64bit Ubuntu. The
> > SIL executable is Tools/MatrixPilot-SIL/matrixpilot and it was built using
> > the command "make -f Makefile.unix matrixpilot" (need to do a "clean"
> > first, if you change any library files).
> > 
> > The options file for the build is
> > "Tools/MatrixPilot-SIL/projectSpecific/options.h" and the plugin I'm using
> > is "Tools/HILSIM_XPlane/prebuilt-plugins/HILSIM-linux_129.xpl"
> > 
> > I noticed some discrepancies between the artificial horizons displayed in
> > Xplane and QGC (pitch appears to be 5-10 degrees to nose-high in QGC), and
> > that the plugin was using the "red board" value for scaleaccel. But
> > changing that value didn't seem to make any difference; perhaps it doesn't
> > matter, but it look to me as though it should.
> > 
> > Anyway, the simulated PT60 is flying a Logo flightplan pretty nicely
> > using angle setpoints for roll and pitch, and it would be nice to see
> > whether anyone could replicate my results.
> > 
> > Also, if the Xplane artificial horizon is "ground truth", then this may
> > indicate a bug in the IMU, at least in my branch. I'd like to do the same
> > comparison using trunk, but haven't been able to make the PT60 fly at all
> > in trunk SILsim. Perhaps someone else is current with the changes to trunk
> > SILsim and can provide some advice.
> > 
> > 73, Mark
> > 
> > On Mon, Sep 15, 2014 at 9:48 AM, Mark Whitehorn kd0aij@gmail.com wrote:
> > 
> > > Pete,
> > > 
> > > It looks like that might be the easiest way for us to collaborate; no
> > > need for me to maintain a separate clone of your fork if I can easily merge
> > > your changes to my repo.  It looks symmetric too; it's just "pull _remotename
> > > branchname"_ to stay up to date with another repo. And it's nice to get
> > > an email letting one know of changes in other forks.
> > > 
> > > 73, Mark
> > > 
> > > On Mon, Sep 15, 2014 at 9:00 AM, Pete Hollands <notifications@github.com
> > > 
> > > > wrote:
> > > > 
> > > > OK, Well I did look at a commit diff on my part of the github website,
> > > > and
> > > > I did press on Pull Request.
> > > > 
> > > > That then gave me a chance to add some comments (which I did not do),
> > > > and
> > > > then I was not aware that I saved the request.
> > > > 
> > > > I will be more careful next time. But no harm done I think. The code is
> > > > prototyped and useful but not yet fully tested and validated.
> > > > 
> > > > Best wishes, Pete
> > > > 
> > > > On 15 September 2014 13:31, Mark Whitehorn notifications@github.com
> > > > wrote:
> > > > 
> > > > > Pete,
> > > > > 
> > > > > :) I found a pull request in my email. And I was going to ask you how
> > > > > to
> > > > > do
> > > > > it, because I've never tried :)
> > > > > 
> > > > > ---
> > > > > 
> > > > > You can merge this Pull Request by running
> > > > > 
> > > > > git pull https://github.com/phollands/MatrixPilot MatrixPilot_mw4fbw
> > > > > 
> > > > > Or view, comment on, or merge it at:
> > > > > 
> > > > > https://github.com/kd0aij/MatrixPilot/pull/1
> > > > > Commit Summary
> > > > > - Initial change to flan.pyw to add a Google Earth Layer for X
> > > > >   acceleration Vectors in body of plane
> > > > > - Plot X accel vector only 5 meters above flight path insteda of 15;
> > > > >   negate pitch value on vector's roll.
> > > > > 
> > > > > File Changes
> > > > > - _M_ Tools/flight_analyzer/flan.pyw
> > > > >   https://github.com/kd0aij/MatrixPilot/pull/1/files#diff-0 (101)
> > > > > - _M_ Tools/flight_analyzer/matrixpilot_lib.py
> > > > >   https://github.com/kd0aij/MatrixPilot/pull/1/files#diff-1 (9)
> > > > > 
> > > > > Patch Links:
> > > > > - https://github.com/kd0aij/MatrixPilot/pull/1.patch
> > > > > - https://github.com/kd0aij/MatrixPilot/pull/1.diff
> > > > > 
> > > > > ---
> > > > > 
> > > > > I just copied the git command in the email above and pushed the
> > > > > result.
> > > > > The python code runs fine for me here.
> > > > > 
> > > > > 73, Mark
> > > > > 
> > > > > On Sun, Sep 14, 2014 at 11:29 PM, Pete Hollands <
> > > > > notifications@github.com>
> > > > > 
> > > > > wrote:
> > > > > 
> > > > > > Did I actually make a Pull Request ? Or did you just decide to Pull
> > > > > > ?
> > > > > > 
> > > > > > Best wishes, Pete
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55554001.
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Mark Whitehorn
> > > > > kd0aij@gmail.com
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55583532.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/kd0aij/MatrixPilot/pull/1#issuecomment-55602960.
> > > 
> > > ## 
> > > 
> > > Mark Whitehorn
> > > kd0aij@gmail.com
> > 
> > ## 
> > 
> > Mark Whitehorn
> > kd0aij@gmail.com

## 

Mark Whitehorn
kd0aij@gmail.com

**Comment by kd0aij** [comment]
Mark,

If you use the same gains as the ones in the options.h file that I sent
you, we can make a direct comparison of two standard cases:
1. Straight and level flying at constant speed and altitude.
2. Constant circle flying at constant speed, altitude, and turn rate, after
   circles settle out to the same path.

Take note of what the two pitch angles are that are displayed. Also take
note whether they are displayed in earth frame or body frame. MatrixPilot
reports pitch in earth frame. The two are not the same.

Best regards,
Bill

**Pull request merged**
